In [51]:
import os
import pandas as pd
import numpy as np

def trim_first_last_n_seconds(df, n, freq):
    remove_indexes = list(range(0, int(n*1000/freq)))
    df = df.drop(remove_indexes)

    remove_indexes = list(range(df.shape[0] - int(n*1000/freq), df.shape[0]-1))
    df = df.drop(remove_indexes)
    
    return df
    

in_dir = "final"
dfs_list = []

features = []
labels = []

for root, dirs, files in os.walk(in_dir):
    path = root.split(os.sep)

    for f in files:
        print("/".join(path) + "/" + f)

        full_path = "/".join(path) + "/" + f
        df = pd.read_csv(full_path, header=None)
        
        print("Before trimming: ", df.shape)
        df = trim_first_last_n_seconds(df, 10, 4)
        print("After trimming: ", df.shape)
   
        #Sample the data according to the size of the window with 50% overlap
        freq = 4
        window_size = 4*1000
        for index in range(0, df.shape[0]-1000, 500):
            indexes = list(range(index, index + int(window_size/freq)))
            
            window = df.iloc[indexes,:]
            
            #Generate the features for this window
            mean_x = np.mean(window[1].tolist())
            mean_y = np.mean(window[2].tolist())
            mean_z = np.mean(window[3].tolist())
            
            var_x = np.var(window[1].tolist())
            var_y = np.var(window[2].tolist())
            var_z = np.var(window[3].tolist())
        
            #Store the features
            window_feature = []
            window_feature.append(mean_x)
            window_feature.append(mean_y)
            window_feature.append(mean_z)
            window_feature.append(var_x)
            window_feature.append(var_y)
            window_feature.append(var_z)
            
            features.append(window_feature)
            
            #Store the label
            labels.append(df[5].iloc[1])
        
        dfs_list.append(df)
        
dfs = pd.concat(dfs_list)        

final/0_1_android.sensor.accelerometer.data.csv
Before trimming:  (64964, 6)
After trimming:  (59965, 6)
final/10_1_android.sensor.accelerometer.data.csv
Before trimming:  (64675, 6)
After trimming:  (59676, 6)
final/11_1_android.sensor.accelerometer.data.csv
Before trimming:  (66938, 6)
After trimming:  (61939, 6)
final/12_1_android.sensor.accelerometer.data.csv
Before trimming:  (60980, 6)
After trimming:  (55981, 6)
final/13_1_android.sensor.accelerometer.data.csv
Before trimming:  (62506, 6)
After trimming:  (57507, 6)
final/14_1_android.sensor.accelerometer.data.csv
Before trimming:  (65108, 6)
After trimming:  (60109, 6)
final/15_1_android.sensor.accelerometer.data.csv
Before trimming:  (62588, 6)
After trimming:  (57589, 6)
final/16_1_android.sensor.accelerometer.data.csv
Before trimming:  (82181, 6)
After trimming:  (77182, 6)
final/17_1_android.sensor.accelerometer.data.csv
Before trimming:  (83784, 6)
After trimming:  (78785, 6)
final/18_1_android.sensor.accelerometer.data.cs

In [81]:
import os
import pandas as pd
import numpy as np

def trim_first_last_n_seconds(df, n, freq):
    remove_indexes = list(range(0, int(n*1000/freq)))
    df = df.drop(remove_indexes)

    remove_indexes = list(range(df.shape[0] - int(n*1000/freq), df.shape[0]-1))
    df = df.drop(remove_indexes)
    
    return df
    
in_dir = "final"
dfs_list = []

features = []
labels = []

for root, dirs, files in os.walk(in_dir):
    path = root.split(os.sep)

    for f in files:
        print("/".join(path) + "/" + f)

        full_path = "/".join(path) + "/" + f
        df = pd.read_csv(full_path, header=None)
        
#         print("Before trimming: ", df.shape)
        df = trim_first_last_n_seconds(df, 10, 4)
#         print("After trimming: ", df.shape)
   
        #Sample the data according to the size of the window with 50% overlap
        freq = 4
        window_size = 4*1000
        for index in range(0, df.shape[0]-1000, 500):
            indexes = list(range(index, index + int(window_size/freq)))
            
            window = df.iloc[indexes,1:df.shape[1]-2]
            
            #Generate the features for this window            
            features.append(np.asarray(window))
            
            #Store the label
            labels.append(df[5].iloc[1])
        
        dfs_list.append(df)
        
dfs = pd.concat(dfs_list)

features = np.asarray(features)
labels = np.asarray(labels)

print(features.shape)
print(labels.shape)
print(features[0])
print(labels[0])

final/0_1_android.sensor.accelerometer.data.csv
final/10_1_android.sensor.accelerometer.data.csv
final/11_1_android.sensor.accelerometer.data.csv
final/12_1_android.sensor.accelerometer.data.csv
final/13_1_android.sensor.accelerometer.data.csv
final/14_1_android.sensor.accelerometer.data.csv
final/15_1_android.sensor.accelerometer.data.csv
final/16_1_android.sensor.accelerometer.data.csv
final/17_1_android.sensor.accelerometer.data.csv
final/18_1_android.sensor.accelerometer.data.csv
final/19_1_android.sensor.accelerometer.data.csv
final/1_1_android.sensor.accelerometer.data.csv
final/2_1_android.sensor.accelerometer.data.csv
final/3_1_android.sensor.accelerometer.data.csv
final/4_1_android.sensor.accelerometer.data.csv
final/5_1_android.sensor.accelerometer.data.csv
final/6_1_android.sensor.accelerometer.data.csv
final/7_1_android.sensor.accelerometer.data.csv
final/8_1_android.sensor.accelerometer.data.csv
final/9_1_android.sensor.accelerometer.data.csv
(2414, 1000, 3)
(2414,)
[[-2.6

In [52]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np
from sklearn.preprocessing import normalize

X = np.array(normalize(features))
y = np.array(labels)

kf = KFold(n_splits=5, random_state=None, shuffle=True)
kf.get_n_splits(X)

acc = []

for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    
    model = LogisticRegression()
    
    model.fit(X_train, y_train)
    
    predicted_labels = model.predict(X_test)
    
    acc.append(accuracy_score(y_test, predicted_labels))
    
print("Accuracy across all folds: ", np.mean(acc))    

Accuracy across all folds:  0.7899762033624562


In [ ]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM, LSTMCell
from keras.layers import Dropout
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np
from sklearn.preprocessing import normalize
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

# X = np.array(normalize(features))
X = features

print(X.shape)

# print(len(y))

y = np.array(labels)
le = preprocessing.LabelEncoder()
y = le.fit_transform(y)

print(y[:5])

y = y.reshape(-1,1)
ohe = OneHotEncoder(sparse=False)
y = ohe.fit_transform(y)

print(y.shape)
# print(len(y))
# kf = KFold(n_splits=5)
# kf.get_n_splits(X)

acc = []

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)

# print(len(X_train))
# print(len(X_test))
# print(len(y_train))
# print(len(y_test))

# print(X_train[0].shape)
# print(len(y_train))

# X_train = X_train.reshape(X_train.shape[0], X_train.shape[1], 1)
# X_test = X_test.reshape(X_test.shape[0], X_test.shape[1], 1)
# y_train = y_train.reshape(y_train.shape[0], 1, 1)
# y_test = y_test.reshape(y_test.shape[0], 1, 1)

# print(X_train[0].shape)
# print(X_test.shape)
# print(y_train.shape)
# print(y_test.shape)

print(X_train.shape)
print(X_train[0].shape[0], X_train[0].shape[1])
print(y_train.shape)

model = Sequential()
model.add(LSTM(100, input_shape=(X_train[0].shape[0], X_train[0].shape[1]), return_sequences=True))
model.add(LSTM(100))
#     model.add(Dropout(0.2))
#     model.add(LSTM(50))
#     model.add(Dropout(0.2))
model.add(Dense(4, activation='softmax'))
#     model.add(Dense(1, activation='sigmoid'))
#     model.compile(loss='mean_squared_error', optimizer='adam')

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

model.summary()

model.fit(X_train, y_train, batch_size=300, epochs=100)

#     predicted_labels = model.predict(X_test)

#     acc.append(accuracy_score(y_test, predicted_labels))


# print("Accuracy across all folds: ", np.mean(acc))    

(1363, 1000, 6)
[1 1 1 1 1]
(1363, 4)
(1226, 1000, 6)
1000 6
(1226, 4)
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_89 (LSTM)               (None, 1000, 100)         42800     
_________________________________________________________________
lstm_90 (LSTM)               (None, 100)               80400     
_________________________________________________________________
dense_70 (Dense)             (None, 4)                 404       
Total params: 123,604
Trainable params: 123,604
Non-trainable params: 0
_________________________________________________________________
Epoch 1/100
1226/1226 [==============================] - 50s 41ms/step - loss: 1.1461 - acc: 0.5481
Epoch 2/100
1226/1226 [==============================] - 44s 36ms/step - loss: 0.7658 - acc: 0.7431
Epoch 3/100
1226/1226 [==============================] - 44s 36ms/step - loss: 0.6029 - acc: 0.8271
Epoch 4/100
 600/1226 [======

In [128]:
from sklearn.metrics import precision_score, recall_score, roc_auc_score

scores = model.evaluate(X_test, y_test, verbose=0)
predicted_labels = model.predict(X_test)

print("Accuracy: ", scores[1]*100)

def get_hot_value(my_list):
    max_val = max(my_list)
    return [int(item == max_val) for item in my_list]

hot_list = [get_hot_value(sublist) for sublist in predicted_labels]

t  = np.array(y_test)
p  = np.array(hot_list)
t = np.argmax(t, axis=1)
p = np.argmax(p, axis=1)

print("Precision: ", precision_score(t, p, average=None))


Accuracy:  85.53719032894482
Precision:  [0.88888889 0.72058824 0.84482759 1.        ]


In [241]:
def combine_acc_gyro_data(df_acc, df_gyro):
    threshold = 10
    
    acc_index = 0
    gyro_index = 0
    
    acc_matrix = df_acc.as_matrix()
    gyro_matrix = df_gyro.as_matrix()
    
#     print(acc_matrix.shape)
#     print(gyro_matrix.shape)
    
    combined_list = []
#     for i in range(3,10):
# #         print(np.concatenate((acc_matrix[i][:], gyro_matrix[i][:])))
#         combined_list.append(np.concatenate((acc_matrix[i][1:4], gyro_matrix[i][1:4])))
    
#     return combined_list
    
    while (acc_index < df_acc.shape[0]) and (gyro_index < df_gyro.shape[0]):
        #find next gyro_index within threshold and append the data
        
        acc_time = df_acc.iloc[acc_index][0]
        gyro_time = df_gyro.iloc[gyro_index][0]

        if (acc_time < gyro_time):
            while (acc_index < df_acc.shape[0]) and (gyro_time - acc_time > threshold):
                acc_time = acc_matrix[acc_index][0] #df_acc.iloc[acc_index][0]
                acc_index += 1
                
#             print(np.concatenate((acc_matrix[acc_index][:4], gyro_matrix[gyro_index][:4]), axis=0))
            
#             combined_list.append(np.concatenate((acc_matrix[acc_index][:4], gyro_matrix[gyro_index][1:6]), axis=0))
        else:
            while (gyro_index < df_gyro.shape[0]) and (acc_time - gyro_time > threshold):
                gyro_time = gyro_matrix[gyro_index][0] #df_gyro.iloc[gyro_index][0]
                gyro_index += 1
            
#             print(np.concatenate((acc_matrix[acc_index][:4], gyro_matrix[gyro_index][:4]), axis=0))
            
        combined_list.append(np.concatenate((acc_matrix[acc_index][:4], gyro_matrix[gyro_index][1:6]), axis=0))
            
#         if (acc_time < gyro_time):
        acc_index += 1
#         else:
        gyro_index += 1
            
#     print(combined_list)
    
    return combined_list

In [242]:
import os
import pandas as pd
import numpy as np

def trim_first_last_n_seconds(df, n, freq):
    remove_indexes = list(range(0, int(n*1000/freq)))
    df = df.drop(remove_indexes)

    remove_indexes = list(range(df.shape[0] - int(n*1000/freq), df.shape[0]-1))
    df = df.drop(remove_indexes)
    
    return df

in_dir = "final"
dfs_list = []

features = []
labels = []

for root, dirs, files in os.walk(in_dir):
    path = root.split(os.sep)

    for f in files:
        
        if 'accelerometer' in f:
            accelerometer_path = "/".join(path) + "/" + f
            print(accelerometer_path)
    
            first_ = f.find("_")
            g = f[0:first_] + "_4" + f[first_+2:]
            gyroscope_path = "/".join(path) + "/" + g.replace("accelerometer","gyroscope")
            print(gyroscope_path)
            
            df_acc = pd.read_csv(accelerometer_path, header=None)
            df_gyro = pd.read_csv(gyroscope_path, header=None)
            
#             print(df_acc.shape)
#             print(df_gyro.shape)
            
            combined_list = combine_acc_gyro_data(df_acc, df_gyro)
            combined_numpy = np.array(combined_list)
            
#             print(combined_list)
            combined_df = pd.DataFrame(data=combined_numpy)
            
#             print(combined_df)
            
            print("Before trimming: ", combined_df.shape)
            combined_df = trim_first_last_n_seconds(combined_df, 10, 4)
            print("After trimming: ", combined_df.shape)
            
            #Sample the data according to the size of the window with 50% overlap
            freq = 4
            window_size = 4*1000
            for index in range(0, combined_df.shape[0]-1000, 500):
                indexes = list(range(index, index + int(window_size/freq)))

                window = combined_df.iloc[indexes, 1:7] #,1:combined_df.shape[1]-2]

                #Generate the features for this window            
                features.append(np.asarray(window))

                #Store the label
                labels.append(combined_df[8].iloc[0])
        
            dfs_list.append(combined_df)
                    
dfs = pd.concat(dfs_list)

features = np.asarray(features)
labels = np.asarray(labels)
            

final/0_1_android.sensor.accelerometer.data.csv
final/0_4_android.sensor.gyroscope.data.csv
Before trimming:  (34142, 9)
After trimming:  (29143, 9)
final/10_1_android.sensor.accelerometer.data.csv
final/10_4_android.sensor.gyroscope.data.csv
Before trimming:  (34053, 9)
After trimming:  (29054, 9)
final/11_1_android.sensor.accelerometer.data.csv
final/11_4_android.sensor.gyroscope.data.csv
Before trimming:  (34366, 9)
After trimming:  (29367, 9)
final/12_1_android.sensor.accelerometer.data.csv
final/12_4_android.sensor.gyroscope.data.csv
Before trimming:  (31982, 9)
After trimming:  (26983, 9)
final/13_1_android.sensor.accelerometer.data.csv
final/13_4_android.sensor.gyroscope.data.csv
Before trimming:  (40277, 9)
After trimming:  (35278, 9)
final/14_1_android.sensor.accelerometer.data.csv
final/14_4_android.sensor.gyroscope.data.csv
Before trimming:  (34135, 9)
After trimming:  (29136, 9)
final/15_1_android.sensor.accelerometer.data.csv
final/15_4_android.sensor.gyroscope.data.csv
Be

In [225]:
print(combined_df.iloc[:5, 1:])

            1        2        3           4  5          6
2500  1.83353  -3.0878   8.9953           0  0  0.0239704
2501  1.85268  -3.0878  8.97615           0  0  0.0239704
2502  1.85268  -3.0878  8.97615  0.00532674  0   0.021307
2503  1.77608 -3.09737  8.97615  0.00532674  0   0.021307
2504  1.75693 -3.12609  9.00487  0.00532674  0   0.021307


In [234]:
print(features[:10])

[[[-2.6377914000000002 0.0 9.148492999999998 0.0 0.0 0.0]
  [-2.6569404999999997 -0.00478728 9.119769 0.0 0.0 0.0]
  [-2.6377914000000002 0.014361841 9.119769 0.0 0.0 0.0]
  ...
  [-2.6569404999999997 0.00478728 9.138917999999999
   -0.007990118000000001 0.0 0.0]
  [-2.6569404999999997 0.00478728 9.138917999999999
   -0.007990118000000001 -0.0026633726 -0.0026633726]
  [-2.647366 0.014361841 9.138917999999999 -0.007990118000000001
   -0.0026633726 -0.0026633726]]

 [[-2.6856642 -0.014361841 9.110194 -0.007990118000000001 0.0 0.0]
  [-2.6856642 -0.014361841 9.110194 -0.007990118000000001 0.0 0.0]
  [-2.6856642 -0.05266008 9.138917999999999 -0.007990118000000001 0.0
   0.0]
  ...
  [-2.6090677 -0.023936402000000002 9.129342999999999 -0.0026633726
   -0.0026633726 0.0]
  [-2.6090677 -0.023936402000000002 9.129342999999999 0.0 0.0 0.0]
  [-2.6090677 -0.043085523 9.158066999999999 0.0 0.0 0.0]]

 [[-2.647366 0.014361841 9.138917999999999 -0.007990118000000001
   -0.0026633726 -0.0026633726]

In [235]:
print(labels[:10])

['sitting' 'sitting' 'sitting' 'sitting' 'sitting' 'sitting' 'sitting'
 'sitting' 'sitting' 'sitting']
